### ISSUE TITLE
Evaluate xi-fixtures for integration or assimilation

### ISSUE THREAD

**Issue by mpartel** [doctrine/data-fixtures#100]
Data fixtures does a good job of providing inheritable static fixtures. I've implemented an alternative, factory-based approach in [Xi Fixtures](https://github.com/xi-project/xi-fixtures), which I've found to often be more flexible and less fragile than static fixtures. It's essentially a [FactoryGirl](https://github.com/thoughtbot/factory_girl) clone for Doctrine.

Is this relevant to your interests? Do you feel the projects should merge? Or maybe just mention each other in their readmes?

**Comment by lavoiesl** [comment]
While your project seems good, it is still a very separate project, I do not believe mentions of it belongs in this project. It would be best to list that kind of alternative in project directories.
