### ISSUE TITLE
[RFC] Use multiple transactions during ORM executor execute()

### ISSUE THREAD

**Issue by alex88** [doctrine/data-fixtures#104]
I'm using lifecycle callbacks to set a default value to a field using an entity got from the db, as https://github.com/doctrine/data-fixtures/blob/master/lib/Doctrine/Common/DataFixtures/Executor/ORMExecutor.php#L75 all the fixtures are loaded in a single commit, this breaks my lifecycle callbacks since the db is not filled with the default data got from another fixture before persisting the entity.

I've fixed this on my repo by using:

    public function execute(array $fixtures, $append = false, $singleTransaction = true)
    {
        $executor = $this;
        if ($singleTransaction) {
            $this->em->transactional(function(EntityManager $em) use ($executor, $fixtures, $append) {
                if ($append === false) {
                    $executor->purge();
                }
                foreach ($fixtures as $fixture) {
                    $executor->load($em, $fixture);
                }
            });
        } else {
            if ($append === false) {
                $executor->purge();
            }
            foreach ($fixtures as $fixture) {
                $executor->load($this->em, $fixture);
            }
        }
    }

which has the problem to break the abstract since only ORM uses transactions or maybe we can add another function to internally set wherever to use a single transaction or not.

Would this be a nice feature to add?

**Comment by lavoiesl** [comment]
Closing in favor of #126
