### ISSUE TITLE
Entity identifiers missing from data in ReferenceRepository

### ISSUE THREAD

**Issue by dsuurlant** [doctrine/data-fixtures#120]
After a fix to the ProxyReferenceRepository it became apparent the data for identifiers is missing from the reference data in some cases, resulting in errors.

For more information, see the comments on https://github.com/doctrine/data-fixtures/commit/8ffac1c63f34124f693b93889fa32f4036eb241b

**Comment by JosephPorta** [comment]
because you have two primary key.. you must pass both like with an array
