### ISSUE TITLE
Assign ID value within referenced Fixture and GeneratedValue(strategy="AUTO")

### ISSUE THREAD

**Issue by JanMalte** [doctrine/data-fixtures#129]
If `@ORM\GeneratedValue(strategy="AUTO")` is used in an entity loaded by a fixture, the ID can't be set manually.

Trying to set it like this will ignore the assigned ID
```php
class TestData extends AbstractFixture {

const IDVALUE = 125;

public function load(ObjectManager $manager)
{
    ...
    $entity->setId(self::IDVALUE);
    ...
}
```

Trying to set it like this will result in the following error
```
Doctrine\ORM\ORMInvalidArgumentException: A new entity was found through the relationship
```

```php
class TestData extends AbstractFixture {

const IDVALUE = 125;

public function load(ObjectManager $manager)
{
    ...
    $entity->setId(self::IDVALUE);
    ...
    // Explicity set ID
    $metadata = $manager->getClassMetaData(get_class($user));
    $metadata->setIdGenerator(new AssignedGenerator());
    ....
}
```
If  `@ORM\GeneratedValue(strategy="AUTO")`  is removed from the entity, the first code works perfect, but the isn't generated in the database anymore.

How can I achieve to set the ID value in a fixture for unit testing but getting it generated in the database for the application code?

**Comment by JanMalte** [comment]
I think it the ID should be automatically saved, if set in a fixture, if set. Having to change the meta data generator in each fixture loading is very much overhead.

**Comment by lavoiesl** [comment]
This is not related to fixtures specifically, but Doctrine itself.
