### ISSUE TITLE
support for embeddable

### ISSUE THREAD

**Issue by cordoval** [doctrine/data-fixtures#157]
i see a branch 2.0 is a rewrite by @guilhermeblanco 

but i see that 1.x still is in good standing and here to stay, so we should make it work with embeddables from doctrine/orm 2.5

my proposal is to work on a PR to enable this to avoid the purger to try to delete the tables that are really just embeddables

anyone can offer guidance on this @Ocramius if so i would like to start a PR mentored in the right direction

Thanks :blush:

**Comment by ferodss** [comment]
I had the same problem. We just need to check if the class to purge is also a embedded class in https://github.com/doctrine/data-fixtures/blob/master/lib/Doctrine/Common/DataFixtures/Purger/ORMPurger.php#L105.

```php
// ...
        foreach ($metadatas as $metadata) {
            if (! $metadata->isMappedSuperclass && ! $metadata->isEmbeddedClass) {
                $classes[] = $metadata;
            }
        }
// ...
```

**Comment by lerox** [comment]
@piteer1 +1
@KingCrunch +1

**Comment by guilhermeblanco** [comment]
Merged as of #172

**Comment by ferodss** [comment]
@guilhermeblanco Packagist is still appoint to an older commit 80401e8a3b6364287b80922fa303fc86d75714db on dev-master

**Comment by nicodmf** [comment]
I have this error since this morning, my composer has : 

        "doctrine/migrations":                                "1.0.*@dev",
        "doctrine/doctrine-migrations-bundle":      "2.1.*@dev",
and 
        "doctrine/data-fixtures":                          "dev-master",
        "doctrine/doctrine-fixtures-bundle":        "*@dev",

I should deploy now and all updates seems make nothing, have you an advice?

**Comment by ferodss** [comment]
"doctrine/data-fixtures": "dev-master" is installing 1.0.0-ALPHA3

**Comment by nicodmf** [comment]
But that doesn't seem correct the error on my env, and i think that the inverse this is the commit that create a problem

**Comment by nicodmf** [comment]
1.0.0-ALPHA3@dev make the work

**Comment by ferodss** [comment]
Which Doctrine ORM are you using? ClassMetadata::$isEmbeddedClass was added on Mar 26, 2013

**Comment by Ocramius** [comment]
Any 2.4.x won't work

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by guilhermeblanco** [comment]
Issue should now be resolved.
