### ISSUE TITLE
Release 1.1?

### ISSUE THREAD

**Issue by jrjohnson** [doctrine/data-fixtures#158]
I see that work is ongoing on 2.0, but there are a bunch of commits on master since the 1.0.0 release that are important.  I would like [8ffac1c63f34124f693b93889fa32f4036eb241b] for example.  Any chance of getting a tagged stable release for packagist?

**Comment by lavoiesl** [comment]
1.0.1 should be released next week: https://github.com/doctrine/data-fixtures/milestones
