### ISSUE TITLE
During DB purge, deletion of self-referential tables result in an error

### ISSUE THREAD

**Issue by georgevanvliet** [doctrine/data-fixtures#159]
If there is an entity ``A`` which has a self referential association, during purge this results in:

```SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails ```

This seems logical. The ORMPurger seems to delete and drop tables in reverse commit order, but doesn't do any such thing for the ```DELETE``` statement on each table.

The only I solution I could come up with (for mysql) is executing the statement ```SET FOREIGN_KEY_CHECKS = 0``` before the ORMPurger does its grunt work.

Is there any solution I overlooked ? If not, what PR can I craft around this ?

Maybe add an option to disable foreign key checks ? Although the necessary statements for that are DB dependent and possibly not implemented on all platforms, there might be a *best effort* option to do so. Could add different "disable foreign key check" strategies for each DB platform.

**Comment by nicolas-bastien** [comment]
@georgevanvliet 
before purge 
$connection->query('SET FOREIGN_KEY_CHECKS=0');

after 
$connection->query('SET FOREIGN_KEY_CHECKS=1');

**Comment by lavoiesl** [comment]
This issue seems to be resolved, please reopen if needed.
