### ISSUE TITLE
Argument 1 passed to Doctrine\Common\DataFixtures\Purger\ORMPurger::__construct()

### ISSUE THREAD

**Issue by ozzmaster** [doctrine/data-fixtures#168]
I started getting this error a few days ago. Not sure what has caused this. This is the error message:
Argument 1 passed to Doctrine\Common\DataFixtures\Purger\ORMPurger::__construct() must be an instance of Doctrine\ORM\EntityManagerInterface, instance of EntityManager54c62feec8075_546a8d27f194334ee012bfe64f629947b07e4919\__CG__\Doctrine\ORM\EntityManager given, called in ~/vendor/doctrine/doctrine-fixtures-bundle/Doctrine/Bundle/FixturesBundle/Command/LoadDataFixturesDoctrineCommand.php on line 100 and defined in ~/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Purger/ORMPurger.php on line 52

Happening on all projects using this bundle and Symfony 2.3.

I would appreciate any help to fix this problem, or some direction if it needs to be logged on a different bundle.

Thanks in advance!

**Comment by stof** [comment]
upgrade to a newer version of the ORM (it looks like you are still using the 2.3 version, which is not maintained anymore since months)

**Comment by krloz1003** [comment]
@ozzmaster find solution?, I have the same problem

**Comment by Hoannv** [comment]
"doctrine/doctrine-fixtures-bundle": "dev-master"

I have the same problem.

**Comment by ozzmaster** [comment]
Hi everyone

I fell back to older/ stable versions. This is an exerpt from my composer.json file after the "fix":

...
    "require": {
        "php": ">=5.3.3",
        "symfony/symfony": "2.3.*",
        "doctrine/doctrine-bundle": "1.2.*",
        "doctrine/doctrine-fixtures-bundle": "2.2.0",
        "doctrine/orm": "~2.2,>=2.2.3",
...
    },
...

I run all my bundles on the dev-master until I get issues like these and get told the "support has ended" or something like that, then over to older bundles.

Starting to think i should stick to stable versions from day 1.

**Comment by krloz1003** [comment]
thanks, i operated only changing "doctrine/orm": "~2.2,>=2.2.3",

**Comment by WickedSilver** [comment]
It works with these bundle versions as well.
```
        "symfony/symfony": "2.4.*",
        "doctrine/orm": ">=2.2.3,<2.4-dev",
        "doctrine/doctrine-bundle": "~1.2",
        "doctrine/doctrine-fixtures-bundle": "2.2.*",
```

Only updated the fixtures bundle to the 2.2 version.

**Comment by darraghenright** [comment]
Upgrading the ORM to 2.4 fixed the problem for me. Thanks @stof :+1:

**Comment by ne0h12** [comment]
Try install doctrine/doctrine-fixtures for version v1.0.0. This is helped for me.

**Comment by lavoiesl** [comment]
This seems to be resolved, if you have other problems, please re-open
