### ISSUE TITLE
Composer update / install stops because of doctrine/data-fixtures

### ISSUE THREAD

**Issue by NV-iloweb** [doctrine/data-fixtures#182]
Updating doctrine/data-fixtures (dev-master bc3c30e => 1.1.x-dev 680e2c8)
    Checking out 680e2c85f980c8bb5e10f2f72a83788387adea57
    680e2c85f980c8bb5e10f2f72a83788387adea57 is gone (history was rewritten?)

**Comment by Ocramius** [comment]
Branch `1.1` was actually removed this morning, I think. Indeed a mistake, but let me remove it from packagist.

**Comment by NV-iloweb** [comment]
Thanks for the quick reply, it works now :+1:
