### ISSUE TITLE
Compatibility break in 1.0.1

### ISSUE THREAD

**Issue by Nek-** [doctrine/data-fixtures#183]
Hello,

I noticed a huge BCBreak in the patch version 1.0.1 here: https://github.com/doctrine/data-fixtures/commit/48ec2812ab8d3c044f975b69a0e834c59b0a4a57#diff-bcb90b22d8706b63fa51389ffc49ddfbR22

This part is not compatible with doctrine 2.3 (that is the default version with [the good old 2.3 standard symfony version](https://github.com/symfony/symfony-standard/blob/v2.3.11/composer.json)).

You can maybe add a warning somewhere... ?

**Comment by stof** [comment]
Doctrine 2.3 is not supported anymore since several months

**Comment by Nek-** [comment]
I'm just saying it should be said somewhere.

Notice that even if doctrine 2.3 is not supported anymore, this is not a good reason to make a big BC Break in what should be a patch :') .

**Comment by stof** [comment]
I agree that it tagging it as 1.0.1 was not the best idea. A fix would be to mark the latest version as conflicting with doctrine/orm 2.3 and older though

**Comment by lavoiesl** [comment]
My bad, I didn't realize this was breaking compat. @stof, how do you suggest I do that? You want to override the 1.0.1 tag?

**Comment by lavoiesl** [comment]
v1.0.2 has the commit reverted, it will be included in 1.1 instead.
