### ISSUE TITLE
Idea: unload method

### ISSUE THREAD

**Issue by cezarykluczynski** [doctrine/data-fixtures#193]
I've just started using this module and I found lack of unload() method puzzling. I'm using it for PHPUnit tests, so setup and teardown are two mandatory steps.

Purger just seems like a disproportionate solution for reverting fixtures.

What if I only want to delete the entities added by current fixtures class, and not purge the entire tables?

I've manage to wire up a unload() method myself. In load() method I'm loading all the created entities to an array, and storing EntityManager as a class property, and later, the unload() method can remove everything.

Stiil, I wonder why unload() isn't there?

**Comment by kim07** [comment]
:+1:

**Comment by dmitryuk** [comment]
No interested persons on feature from 2015. Should we close the issue?

**Comment by greg0ire** [comment]
Let's close; there are IMO [better ways to do this](https://packagist.org/packages/dama/doctrine-test-bundle)
