### ISSUE TITLE
[DX] Add fixtures:load Command

### ISSUE THREAD

**Issue by L0rD59** [doctrine/data-fixtures#196]
Hi,

It would be great to have the fixtures:load Command in this project for standalone usage. 

Actually the fixtures:load Command is in DataFixturesBundle for symfony context.

What do you think about that ?

**Comment by zeroedin-bill** [comment]
There is a PR open for this: https://github.com/doctrine/data-fixtures/pull/49

**Comment by L0rD59** [comment]
K thx,

sorry for disturb.
