### ISSUE TITLE
problem compatibility mysql/postgresql doctrine (fixtures)

### ISSUE THREAD

**Issue by mreichstadt** [doctrine/data-fixtures#205]
Hello,
We are trying to load fixtures from our symfony2 application but we are getting into trouble.

Here is what we have in our User entity.
/**
- User
  *
- @ORM\Table(schema="admin",name="si_parcelle_user")
- @ORM\Entity(repositoryClass="Application\UserBundle\Entity\UserRepository")
  */

When we create the database we don't get any errors, everything is ok, but when we try to load the Data Fixtures for the User entity, we get an error message telling us that the table si_parcelle_user is undefined.

Does anyone know if we did something wrong?

thank you very much in advance

**Comment by mreichstadt** [comment]
I've seen that I get another error. If I try to let this configuration for my entity with the schema and if I try to upload the database using this time mysql, the table is not created. I thought that it wasn't taken into account (the schema) if we used mysql, but apparently I was wrong? 

thank you again ^^

**Comment by plfort** [comment]
hello, try to use the master branch. I think you problem is solve with this PR : #202

**Comment by skobkin** [comment]
@plfort Seems like work for me.

Before:

```
$ sf doc:fix:loa --fixtures="src/AppBundle/DataFixtures/ORM/LoadOccupationData."
Careful, database will be purged. Do you want to continue y/N ?y
  > purging database                                                                                  
  [Doctrine\DBAL\Exception\TableNotFoundException]                                  
  An exception occurred while executing 'DELETE FROM buyer_data':                   
  SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "buyer_data" does not exist  
  LINE 1: DELETE FROM buyer_data 
...
```

Then

```
$ composer update doctrine/data-fixtures                                                                                                                                                     [±feature_online_order ●●●▴]
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Loading composer repositories with package information
Updating dependencies (including require-dev)         
  - Removing doctrine/data-fixtures (v1.1.1)
  - Installing doctrine/data-fixtures (dev-master b4213c2)
    Cloning b4213c21f138c96c29ba2f57349d6fca5b2878a9
...
```

After:

```
$ sf doc:fix:loa --fixtures="src/AppBundle/DataFixtures/ORM/LoadOccupationData."
Careful, database will be purged. Do you want to continue y/N ?y
  > purging database
  > loading AppBundle\DataFixtures\ORM\LoadCategoryData
```

**Comment by mikeSimonson** [comment]
@skobkin Thanks
