### ISSUE TITLE
No Exception thrown if a order-number is used twice

### ISSUE THREAD

**Issue by OskarStark** [doctrine/data-fixtures#218]
There should be an Exception if a number for the ordering is used twice.

I have 2 Fixtures, which are using:

``` php
    public function getOrder()
    {
        return 5100;
    }
```

**Comment by SimonHeimberg** [comment]
I guess this is expected. You can use this when the order between this two does not matter. The execution order of this two fixtures is undefined, but the order relative to other numbers is clear.

**Comment by Ocramius** [comment]
Closing as per comment of @SimonHeimberg.

If this is still to be considered a bug, then a failing test case is required first.
