### ISSUE TITLE
object manager does not fetch previously persisted objects

### ISSUE THREAD

**Issue by cordoval** [doctrine/data-fixtures#219]
Prior to fixtures i fill the table diagnosis with data via  a console command. Then after i run fixtures and within one of them i try to fetch diagnosis objects, however the result is always empty.

Is doctrine manager loading any different from a regular controller?
```php
$diagnosis = $this->container->get('doctrine')->getManager()->getRepository('Diagnosis:Diagnosis')->findAll();
```

**Comment by stof** [comment]
By default, existing data are removed before loading fixtures
