### ISSUE TITLE
TopologicalSorter breaks purge with foreign key constraints

### ISSUE THREAD

**Issue by peterrehm** [doctrine/data-fixtures#230]
It breaks with SQL errors regarding Integrity constraint violations.

Related to #228.

**Comment by dominikzogg** [comment]
@Ocramius thanks for the new version, we have the same problem on purge

```
Method setUpFixtures (Namespace\To\TestClass) has encountered an PDO Exception: An exception occurred while executing 'DELETE FROM entityname':
     [exec] 
     [exec] SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`databasename`.`some_relation_table`, CONSTRAINT `FK_.....` FOREIGN KEY (`parent_id`) REFERENCES `yetanothertable` (`id`))
```

**Comment by Ocramius** [comment]
Description and error reports are not sufficient without an actual example or test-case.

**Comment by Ocramius** [comment]
> @Ocramius the order to cleanup the tables does not or not complete consider the foreign_keys

Yes, that is understood.

 1. what are the defined fks?
 2. what are the defined tables/entities?
 3. what are the SQL operations performed
 4. in which order are they queued? (required to see how ordering logic needs to be adjusted)

**Comment by mgonyan** [comment]
@Ocramius i think the error is  due to:
- The getCommitOrder function if it adds a node again it overrides its relations
- The sort method of TopologicalSorter gives us the list of tables already ordered, so they don't need to be ordered again. 
I am working on the test, so please have a look at the PR #231

**Comment by dominikzogg** [comment]
@Ocramius https://github.com/doctrine/data-fixtures/pull/234, that is what i would expect, trying to delete a Role

**Comment by mgonyan** [comment]
@dominikzogg why would you expect that output  (`users.role_id` column) when the function `getAssociationTables` returns all the joinTables to be truncate/delete their content as a first step in the purge process ?

**Comment by dominikzogg** [comment]
@mgonyan As you can see, the other test, returns the same format. Deleteting a role is not possible in this case, without setting the column users.role_id to null or delete the users (see existing test classes).

**Comment by Snowbaha** [comment]
Hi,

I have the same problem since I upgraded mysql to 5.5.49 (before 5.5.41) and same issue with mysql 5.7.*

I don't understand why a "minor" version can break all the fixture with the purge... :(

**Comment by peterrehm** [comment]
@Snowbaha As you can see there are attempts to find a solution. You can require a version < 1.2 as immediate fix and support the resolution of the issues.

**Comment by Ocramius** [comment]
> I don't understand why a "minor" version can break all the fixture with the purge... :(

We had to rewrite the entire purger logic because it was relying on internal ORM classes (that were specifically marked as internal). ORM is changing with 2.6, so we couldn't rely on those classes anymore.

The problem was data-fixtures relying on those internals anyway.

**Comment by peterrehm** [comment]
@Ocramius Would it eventually be possible to disable foreign key checks purge all and reenable that? Ever since I had the issue that purging worked on my complex app only on the clean structure su I had put some logic around that. However I don't know if this would work cross-db.

**Comment by Ocramius** [comment]
It would not work cross-db => not implemented in data-fixtures (which knows only about ORM, basically)

**Comment by stof** [comment]
See #239 which should solve things as long as your graph is not cyclic

**Comment by mikeSimonson** [comment]
Can you confirm that this is fixed in https://github.com/doctrine/data-fixtures/releases/tag/v1.2.2 ?

**Comment by Snowbaha** [comment]
Hey!
Yep it looks to be working now, thank you ;)
In the same time, I did a SQLlite database to test to avoid the problem. But if I re-switch with my preview path and your update, it is working :)

**Comment by mikeSimonson** [comment]
@Snowbaha Thanks for the feedback

**Comment by videni** [comment]
I have this issue today  at `doctrine/data-fixtures    v1.3.2 `, what I did wrong? 



Order.orm.xml
```
<doctrine-mapping xmlns="http://doctrine-project.org/schemas/orm/doctrine-mapping"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xmlns:gedmo="http://gediminasm.org/schemas/orm/doctrine-extensions-mapping"
                  xsi:schemaLocation="http://doctrine-project.org/schemas/orm/doctrine-mapping
                                      http://doctrine-project.org/schemas/orm/doctrine-mapping.xsd">

    <entity name="Acme\Bundle\OrderBundle\Entity\Order" table="acme_order">
        <id name="id" column="id" type="integer">
            <generator strategy="AUTO" />
        </id>
        <one-to-one field="review" target-entity="Acme\Bundle\ReviewBundle\Entity\OrderReview" mapped-by="reviewSubject"/>
        <one-to-one field="report" target-entity="Acme\Bundle\ReportBundle\Entity\Report" mapped-by="order"/>
    </entity>
</doctrine-mapping>
```

OrderReview.orm.xmln
```
<doctrine-mapping xmlns="http://doctrine-project.org/schemas/orm/doctrine-mapping">
    <entity name="Acme\Bundle\ReviewBundle\Entity\OrderReview" table="acme_order_review">
     <id name="id" column="id" type="integer">
            <generator strategy="AUTO" />
        </id>
        <one-to-one field="reviewSubject" inversed-by="review" target-entity="Acme\Bundle\OrderBundle\Entity\Order"/>
    </entity>
</doctrine-mapping>

```

Report.orm.xml
```
<doctrine-mapping xmlns="http://doctrine-project.org/schemas/orm/doctrine-mapping"
                  xmlns:gedmo="http://gediminasm.org/schemas/orm/doctrine-extensions-mapping"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://doctrine-project.org/schemas/orm/doctrine-mapping
                                      http://doctrine-project.org/schemas/orm/doctrine-mapping.xsd">

    <entity name="Acme\Bundle\ReportBundle\Entity\Report" table="acme_auto_report"  >
        <id name="id" column="id" type="integer">
            <generator strategy="AUTO" />
        </id>

        <one-to-one field="order" inversed-by="report" target-entity="Acme\Bundle\OrderBundle\Entity\Order" nullable="false"/>
       
    </entity>

</doctrine-mapping>
```

the the result table orders are following, but `acme_auto_report` table hold foreign key to acme_order, it must be before the `acme_order` table.
```
26 => "acme_order_review"
  27 => "acme_order"
  34 => "acme_auto_report"
```

**Comment by alcaeus** [comment]
@videni Can you please create a separate issue for this? The issue at hand was fixed, and I don't want to reopen it. Thanks!
