### ISSUE TITLE
CircularReferenceException

### ISSUE THREAD

**Issue by nurolopher** [doctrine/data-fixtures#232]
Guys I having an issue while trying to load fixtures for an entity with a tree behavior. You can see my entity on [gist](https://gist.github.com/nurolopher/c0f2372b4348bc8c581a7eb3ca1f9a2a). Did anyone have issue like this and how did you solve it?

**Comment by Ocramius** [comment]
See similar issues, like https://github.com/doctrine/data-fixtures/issues/230, https://github.com/doctrine/data-fixtures/issues/231

Closing as duplicate.

**Comment by nurolopher** [comment]
@Ocramius It looks like not a duplicate issue. #230 , #231 don't deal with a circular reference error as shown below:
`[Doctrine\Common\DataFixtures\Exception\CircularReferenceException]                                                                                                                           
  Graph contains cyclic dependency. An example of this problem would be the following: Class C has class B as its dependency. Then, class B has class A has its dependency. Finally, class A h  
  as class C as its dependency.`

I am getting this error because of self-referencing properties like:
```
/**
     * @Gedmo\TreeParent
     * @ORM\ManyToOne(targetEntity="Category", inversedBy="children")
     * @ORM\JoinColumn(referencedColumnName="id", onDelete="CASCADE")
     */
    private $parent;

    /**
     * @ORM\OneToMany(targetEntity="Category", mappedBy="parent")
     * @ORM\OrderBy({"lft" = "ASC"})
     */
    private $children;

**Comment by Ocramius** [comment]
Are you already on `1.2.1`? We fixed that in https://github.com/doctrine/data-fixtures/pull/229, as far as I know

**Comment by nurolopher** [comment]
@Ocramius thanks 👍 . My version was 1.2.0. Just updated and it's working fine.

**Comment by KevinRaimbaud** [comment]
I have the same problem, but I'm using the `1.2.1`. How can I fix that?
Here is my Entity: https://gist.github.com/KevinRaimbaud/22d5d865efe4dcb7aa5487c65012bad4

**Comment by PorridgeBear** [comment]
Also ran into this problem today with a self-referencing ManyToOne property. Also using 1.2.1 and whilst we normally use Alice, too, the issue also presents when running the standard doctrine:fixtures:load.
