### ISSUE TITLE
Graph contains cyclic dependency

### ISSUE THREAD

**Issue by mvar** [doctrine/data-fixtures#236]
I run into this exception when I try to load fixtures:

```bash
$ bin/console doctrine:fixtures:load -n -vvv
  > purging database

                                                                                                                     
  [Doctrine\Common\DataFixtures\Exception\CircularReferenceException]                                                
  Graph contains cyclic dependency. An example of this problem would be the following: Class C has class B as its d  
  ependency. Then, class B has class A has its dependency. Finally, class A has class C as its dependency.           
                                                                                                                     

Exception trace:
 () at /Users/mantas/Sites/xxx/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Sorter/TopologicalSorter.php:158
 Doctrine\Common\DataFixtures\Sorter\TopologicalSorter->visit() at /Users/mantas/Sites/xxx/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Sorter/TopologicalSorter.php:165
 Doctrine\Common\DataFixtures\Sorter\TopologicalSorter->visit() at /Users/mantas/Sites/xxx/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Sorter/TopologicalSorter.php:112
 Doctrine\Common\DataFixtures\Sorter\TopologicalSorter->sort() at /Users/mantas/Sites/xxx/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Purger/ORMPurger.php:197
 Doctrine\Common\DataFixtures\Purger\ORMPurger->getCommitOrder() at /Users/mantas/Sites/xxx/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Purger/ORMPurger.php:111
 Doctrine\Common\DataFixtures\Purger\ORMPurger->purge() at /Users/mantas/Sites/xxx/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/AbstractExecutor.php:136
 Doctrine\Common\DataFixtures\Executor\AbstractExecutor->purge() at /Users/mantas/Sites/xxx/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/ORMExecutor.php:85
 Doctrine\Common\DataFixtures\Executor\ORMExecutor->Doctrine\Common\DataFixtures\Executor\{closure}() at n/a:n/a
 call_user_func() at /Users/mantas/Sites/xxx/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:233
 Doctrine\ORM\EntityManager->transactional() at /Users/mantas/Sites/xxx/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/ORMExecutor.php:90
 Doctrine\Common\DataFixtures\Executor\ORMExecutor->execute() at /Users/mantas/Sites/xxx/vendor/doctrine/doctrine-fixtures-bundle/Command/LoadDataFixturesDoctrineCommand.php:118
 Doctrine\Bundle\FixturesBundle\Command\LoadDataFixturesDoctrineCommand->execute() at /Users/mantas/Sites/xxx/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at /Users/mantas/Sites/xxx/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:831
 Symfony\Component\Console\Application->doRunCommand() at /Users/mantas/Sites/xxx/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:186
 Symfony\Component\Console\Application->doRun() at /Users/mantas/Sites/xxx/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:80
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /Users/mantas/Sites/xxx/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:117
 Symfony\Component\Console\Application->run() at /Users/mantas/Sites/xxx/bin/console:29
```

Fixtures are loaded when using version __v1.1.1__ of this library. 
Does not work with __v1.2.1__ or __v1.2.0__.

And... how I'm supposed to know where is the issue? Why does exception message prints `A`, `B`, `C` instead of real class names? I have ~100 entities (including embeddables).

---

More about my case:

I have 3 level hierarchy which is made up with two additional classes. Top and bottom levels extends abstract class (single table inheritance). Middle level is of two types, so it has another abstract class which extends the first one. These levels are connected with parent-children relations which is described in main abstract class. Other classes just holds specific type and setter/getters for parent/children where needed.

I'm not sure what's wrong, but `CircularReferenceException` exception is thrown while processing main abstract class.

**Comment by megyland** [comment]
I have the same issue, fixtures are loaded when using **v1.1.1** but it doesn't work with **v1.2.0** and **v1.2.1** and I get the same exception

**Comment by simoziyadi** [comment]
I also have the same problem could anyone tell me how to fix it.

**Comment by totaltrash** [comment]
I have the same issue with a schema that uses inheritance see #227.

**Comment by Renrhaf** [comment]
Same issue here.

**Comment by cordoval** [comment]
This is because @Ocramius did some refactoring, i had solve it with tying the dependencies instead of

```bash
       "doctrine/doctrine-fixtures-bundle": "~2.3.0",
       "doctrine/data-fixtures": "~1.1.1",
```

to:

```bash
     "doctrine/doctrine-fixtures-bundle": "~2.3.0",
     "doctrine/data-fixtures": "1.1.1",
```
I think there was a wrong tagging somewhere because ~1.1.1 installed 1.2.0 which does not make sense. But in any case, there is your solution we can close this ticket after you guys confirm.

**Comment by mvar** [comment]
@cordoval sticking to old version is not a solution.

**Comment by cordoval** [comment]
he he, it seems it is for sylius too. Not saying new code is not good. Just saying old code was not holding me back.

**Comment by peterrehm** [comment]
There is ongoing work in #231. With the minor improvement in #233 you will see the classes causing the exception.

**Comment by Ocramius** [comment]
Sticking to `1.1.*` is a good-enough solution for now. ORM 2.6 will not be compatible with it, though.

**Comment by stof** [comment]
@Ocramius the 1.1 version was not breaking on purge for circular references (it may break at the DB level if you don't have ``ON DELETE`` behavior configured for your constraints, but it would allow to work with cyclic graphs).
Throwing an exception instead of silently accepting cyclic graphs with the same limitation is a BC break, so not good for a minor version. And there is no workaround (contrary to the 1.1.x behavior where you could solve it by changing the ON DELETE behavior of your constraint in the DB)

**Comment by Jean85** [comment]
Same issue here too, revert of composer update was the only solving way.

@Ocramius , why are you stopping to support cyclic definitions of entities? It's commonly used...

**Comment by stof** [comment]
@Ocramius I think we would need to have a way to make the TopologicalSorter accept cyclic references for entities (their order is then undefined, and you have to ensure that the DB constraints can handle the removal of cycles) but keep being strict for the sorting of fixtures
