### ISSUE TITLE
Problem with ORMPurge and dependencyList

### ISSUE THREAD

**Issue by skjaro** [doctrine/data-fixtures#244]
There is bug in getCommitOrder which adds multiple times same node which clears dependencyList in TopologicalSorter instance.

        foreach ($classes as $class) {
            $sorter->addNode($class->name, $class);

**should be:**

        foreach ($classes as $class) {
            if ( ! $sorter->hasNode($class->name))
                    $sorter->addNode($class->name, $class);

becouse code bellow already adds class in associationMappings:

                    if ( ! $sorter->hasNode($targetClassName)) {
                        $sorter->addNode($targetClassName, $targetClass);
                    }

                    // add dependency ($targetClass before $class)
                    $sorter->addDependency($targetClassName, $class->name);

**Comment by mikeSimonson** [comment]
@skjaro Can you make a test case and a PR for it ?

**Comment by skjaro** [comment]
I will try, but I look at pull request #240 there  is already fixed this issue.

**Comment by skjaro** [comment]
Definitely, #240 fix my issue. I tested it today, please merge.

**Comment by mikeSimonson** [comment]
closed by #240
