### ISSUE TITLE
Attributes are not populated with sharing objects

### ISSUE THREAD

**Issue by Kwadz** [doctrine/data-fixtures#249]
When I reference an object which has attributes populated:

![screen_shot_2017-01-18_at_16_45_11](https://cloud.githubusercontent.com/assets/1472599/22070957/fe4b834c-dd9d-11e6-8b99-22c350385d1e.png)

The attribute values disappear (except id) when I get the reference:

![screen_shot_2017-01-18_at_16_44_22](https://cloud.githubusercontent.com/assets/1472599/22070964/02a75dd0-dd9e-11e6-8dc5-276c10d36cfc.png)

**Comment by stof** [comment]
This is because you are getting a non-initialized proxy (which will get initialized when you call anything else that ``getId()`` on it, because each fixture is loaded separately and the EM is cleared between them (avoiding to do a flush on a huge unit of work the last time).
There is nothing wrong here.

**Comment by Kwadz** [comment]
How do you suggest to initialize the proxy?


```php
class ProcessorDataLoader extends AbstractFixture implements OrderedFixtureInterface
{
    public function load(ObjectManager $manager) {
        $myProcessor = new Processor();
        $myProcessor->setFactory("PaypalTransactionProcessor");
        $myProcessor->setName("PaypalTransactionProcessor");

        $manager->persist($myProcessor);
        $manager->flush();

        $this->addReference('my-processor', $myProcessor);
    }
}
```

```php
class TransactionDataLoader extends AbstractFixture implements OrderedFixtureInterface
{
    private $maVar;
    public function load(ObjectManager $manager) {
        $transaction = new PaymentTransaction();
        $processor = $this->getReference("my-processor");
        $transaction->setProcessor($processor);
        $transaction->setAmount(60);
        $transaction->setCurrency("EUR");

        $manager->persist($transaction);
        $manager->flush();
    }
}
```

**Comment by mikeSimonson** [comment]
@Kwadz You typically initialize a proxy by calling a getter on a not initialized property (not the id).
But it doesn't matter in your case for your code to work you only need the id of your processor.

Close as invalid.
Don't hesitate to reopen if you have clarification about an issue.

**Comment by Kwadz** [comment]
Do you suggest initializing a proxy by calling a getter like this:

```php
class ProcessorDataLoader extends AbstractFixture implements OrderedFixtureInterface
{
    public function load(ObjectManager $manager) {
        $myProcessor = new Processor();
        $myProcessor->setFactory("PaypalTransactionProcessor");
        $myProcessor->setName("PaypalTransactionProcessor");

        $manager->persist($myProcessor);
        $manager->flush();

        ** $myProcessor->getName(); **

        $this->addReference('my-processor', $myProcessor);
    }
}
```

**Comment by mikeSimonson** [comment]
You don't need to initialize it. As soon as your code will need something from that processor it will initialize itself automatically, you don't need to do anything.
The only reason why it's not initialized yet is because no part of your code needed it.

**Comment by Kwadz** [comment]
In all cases it should be at least usable by the other fixtures during the creation. And here it is not the case.

I made a new test. I realized the problem occurs during the second pass (many fixtures need the `hotel-item-group` reference).

**First pass:**

<img width="842" alt="capture_d_ecran_12_02_2017_01_54" src="https://cloud.githubusercontent.com/assets/1472599/22858786/a6990f42-f0c7-11e6-8d23-59319fa525a5.png">

**Second pass:**

<img width="840" alt="capture_d_ecran_12_02_2017_01_56" src="https://cloud.githubusercontent.com/assets/1472599/22858788/bbe7a0c0-f0c7-11e6-9121-cd826aebedbf.png">

So, I get:
```
[PDOException]
  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'item_group_id' cannot be null
```

**Comment by Kwadz** [comment]
To reproduce the error, I updated [this repo](https://github.com/Kwadz/alice-test) which contains everything needed. 
You just need to create the db and execute `DefaultControllerTest::testLoadFixtures()`

**Comment by Kwadz** [comment]
> Don't hesitate to reopen if you have clarification about an issue.

@mikeSimonson I can't repoen the issue as it's not me who closed it. Can you reopen it please ?

**Comment by Kwadz** [comment]
In fact the `@ORM\JoinColumn` name was wrong. So, the issue came from the `Offer` entity configuration.
