### ISSUE TITLE
serialize/unserialize of ProxyReferenceRepository break custom Doctrine types

### ISSUE THREAD

**Issue by JustBlackBird** [doctrine/data-fixtures#254]
I'm using Entities with columns of custom Doctrine types (ex. [UUID type](https://github.com/ramsey/uuid-doctrine)).

I have a user entity:

```php
use Ramsey\Uuid\UuidInterface;

/**
 * @Entity
 */
class User
{
      /**
       * @Id
       * @Column(type="uuid")
       * @var UuidInterface
       */
      private $id;

      public function __construct(UuidInterface $id)
      {
          $this->id = $id;
      }

      public function getId()
      {
          return $this->id;
      }
}
```

When I run:

```php
$id = Ramsey\Uuid\Uuid::uuid4();
$user = new User($id);

$repo = new ProxyReferenceRepository($em);
$repo->add('user', $user);

$serialized_data = $repo->serialize();
$repo_copy = new ProxyReferenceRepository($em);
$repo_copy->unserialize($serialized_data);

$user_copy = $repo_copy->getReference('user');
```

I get a broken User entity:

```php
echo(is_string($user_copy->getId()) ? 'broken' : 'not sure'); // Outputs "broken"
```

In other words serialization inside of `ProxyReferenceRepository` does not unserialize correctly attached objects which are not Entities.

____

I've look at the code of `ProxyReferenceRepository` and saw [this](https://github.com/doctrine/data-fixtures/blob/master/lib/Doctrine/Common/DataFixtures/ProxyReferenceRepository.php#L72):

```php
        $serializedData = json_encode(array(
            'references' => $simpleReferences,
            'identities' => $this->getIdentities(),
        ));
```

and [this](https://github.com/doctrine/data-fixtures/blob/master/lib/Doctrine/Common/DataFixtures/ProxyReferenceRepository.php#L87):

```php
        $repositoryData = json_decode($serializedData, true);
        $references     = $repositoryData['references'];
```

The question is why `json_encode`/`json_decode` are used here instead of `serialize`/`unserialize`? As far as I can see such change does not break anything but make the library play nice with columns of custom Doctrine types.

**Comment by JustBlackBird** [comment]
Any news on this?

**Comment by Ocramius** [comment]
@JustBlackBird it needs a test case, but yes, `serialize` and `unserialize` would be more appropriate.

**Comment by JustBlackBird** [comment]
@Ocramius Thanks for the response. I'll provide a PR soon.
