### ISSUE TITLE
Purger cannot purge tables with special names

### ISSUE THREAD

**Issue by bugadani** [doctrine/data-fixtures#258]
I have a table named 'order' which ORMPurger is not able to purge because it does not quite the table name properly.

[Doctrine\DBAL\Exception\SyntaxErrorException]
  An exception occurred while executing 'DELETE FROM order':
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that
   corresponds to your MariaDB server version for the right syntax to use near 'order' at line 1

**Comment by Ocramius** [comment]
Table should be mapped as following (or equivalent) in order for the quoting strategy to pick it up:

```php
@ORM\Column(name="`order`")
```

**Comment by bugadani** [comment]
Curiously it works everywhere else and even if I choose truncate over delete as the purging method. I accept that I should configure my stuff correctly but if something fails in one place only, I don't believe that is my fault.

**Comment by Ocramius** [comment]
It may be that the method is not quoting correctly, for which we'd start
from a test case in ORM first.

The idea is that if there is a bug, in general, we should fix the cause,
not the effects: I pointed you to the entrance of the rabbit hole if you
want to explore 😁

**Comment by bugadani** [comment]
Very well, thank you for your time and effort 👍
