### ISSUE TITLE
Set Container Is Not Working When Implements ContainerAwareInterface

### ISSUE THREAD

**Issue by welenlin** [doctrine/data-fixtures#268]
Hello, 
I already try to inject container based on the documentation [here](http://symfony.com/doc/current/bundles/DoctrineFixturesBundle/index.html) and still not working, is there something wrong with my code or the DI itself is not working ?

doctrine fixture version: "doctrine/doctrine-fixtures-bundle": "2.2.*",
symfony version : 2.8.7

```
class LoadDataDefault extends AbstractFixture implements ContainerAwareInterface
{

    /**
     * @var ContainerInterface $container
     */
    private $container;

    public function setContainer(ContainerInterface $container = null)
    {
        $this->container = $container;
    }

}
```

Thanks :)

**Comment by stof** [comment]
well, what do you mean by "is not working" ? What is the error you get ?

**Comment by welenlin** [comment]
@stof 
when i try to var_dump("test");exit; in the setContainer , it doesnt trigger the var_dump so i'm assuming that   it doesnt call the setContainer function method, and in the load() method i tried to use $this->container->get('session'); it triggers "fatal error: Call to a member function get() on null"

**Comment by Ocramius** [comment]
@welenlin that needs an example on how to reproduce the issue: the fixture loader on its own doesn't do the injection on its own, that's done by symfony-specific details while running the CLI command.

**Comment by welenlin** [comment]
@Ocramius did you mean that i should run doctrine:fixtures:load in order to inject the container  ?

**Comment by Ocramius** [comment]
@welenlin yes: the functionality provided by the raw doctrine/data-fixtures has no container awareness.

**Comment by welenlin** [comment]
@Ocramius is there any other way than running the command ? since i'm using it in integration test case with the setup loadFixturesFromDirectory and i need to access the container there

**Comment by Ocramius** [comment]
As I already said, this package does know *nothing* about the container: it is a purely symfony-bundle-specific feature.

**Comment by alcaeus** [comment]
@welenlin the magic is done by the DataFixtures bridge within Symfony, namely [`Symfony\Bridge\Doctrine\DataFixtures \ContainerAwareLoader`](https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Doctrine/DataFixtures/ContainerAwareLoader.php).

**Comment by welenlin** [comment]
@Ocramius @alcaeus 

Okay I understand now, thanks for the help :)
