### ISSUE TITLE
Compatibility with Doctrine 2.6

### ISSUE THREAD

**Issue by danrot** [doctrine/data-fixtures#281]
We are using this library for our tests, and one part is to purge the database when necessary. However, since the release of Doctrine 2.6 I am getting the following error:

```
1) Sulu\Bundle\AdminBundle\Controller\AdminControllerTest::testIndexAction
Error: Call to undefined method Doctrine\ORM\Internal\CommitOrderCalculator::addClass()

/Users/daniel.rotter/Development/massiveart/sulu-test/vendor/sulu/sulu/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Purger/ORMPurger.php:148
/Users/daniel.rotter/Development/massiveart/sulu-test/vendor/sulu/sulu/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Purger/ORMPurger.php:111
/Users/daniel.rotter/Development/massiveart/sulu-test/vendor/sulu/sulu/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/AbstractExecutor.php:136
/Users/daniel.rotter/Development/massiveart/sulu-test/vendor/sulu/sulu/src/Sulu/Bundle/TestBundle/Testing/SuluTestCase.php:285
/Users/daniel.rotter/Development/massiveart/sulu-test/vendor/sulu/sulu/src/Sulu/Bundle/AdminBundle/Tests/Functional/Controller/AdminControllerTest.php:27
```

I've doublechecked it, and the method that is called in the `ORMPurger` really does not exist anymore... Can this be fixed in some way?

**Comment by alcaeus** [comment]
This has been removed in v1.2.0 more than a year ago. Please update.

**Comment by danrot** [comment]
Oh, wasn't aware there was already a new release... Sorry to bother you!

**Comment by alcaeus** [comment]
`composer outdated` will help you spot those. In this case, it's sulu/sulu that locks it to `1.1.*`.

**Comment by danrot** [comment]
Already fixed that, just didn't think of even trying that 🙈 But it is a little bit weird, that the `doctrine/orm` is not a requirement, if the code from there is being used? Or was that dependency also removed as well?

**Comment by alcaeus** [comment]
It's a soft requirement: the library can also be used with MongoDB ODM. This should/could be solved more explicit (by splitting this library into the generic and the parts specific to various mappers), but it's not worth the hassle.
