### ISSUE TITLE
History rewritten?

### ISSUE THREAD

**Issue by robocoder** [doctrine/data-fixtures#286]
I can see the commit here:  https://github.com/doctrine/data-fixtures/commit/83a910f62b01715f3ed7317f5a4996417a698177

but when I clone the project, it can't be found.
```
$ git show 83a910f62b
fatal: ambiguous argument '83a910f62b': unknown revision or path not in the working tree.
```

**Comment by Ocramius** [comment]
@robocoder shallow clone or didn't fetch all branches? Maintenance branches do diverge from `master`.

**Comment by robocoder** [comment]
I guess someone promoted a different branch to master.  The commit is now cf25ce305180fa279a6ef18547e94f6347e77620.

**Comment by robocoder** [comment]
Weird. My composer.json doesn't contain any references to doctrine/data-fixtures.

It was my composer.lock that had:
```
            "name": "doctrine/data-fixtures",
            "version": "dev-master",
            "source": {
                "type": "git",
                "url": "https://github.com/doctrine/data-fixtures.git",
                "reference": "83a910f62b01715f3ed7317f5a4996417a698177"
            },
```
and all the packages that listed it as a dependency required either
```
"doctrine/data-fixtures": "1.0.*",
```
or
```
"doctrine/data-fixtures": "~1.0",
```
