### ISSUE TITLE
doctrine/doctrine-bundle 1.9.0 breaks FixtureInterface

### ISSUE THREAD

**Issue by InputOutput** [doctrine/data-fixtures#293]
The FixtureInterface uses the ObjectManager for typehinting in load(). See: https://github.com/doctrine/data-fixtures/blob/master/lib/Doctrine/Common/DataFixtures/FixtureInterface.php

The ObjectManager has been deprecated in favour of the EntityManagerInterface in doctrine-bundle 1.9.0

**Comment by mikeSimonson** [comment]
Already fixed in 1.9.1 where that commit has been reverted.

**Comment by InputOutput** [comment]
Ok thanks, are ObjectManager and ManagerRegistry still deprecated and planned to be removed in later versions or not?
