### ISSUE TITLE
Question: Add more options to Purger 

### ISSUE THREAD

**Issue by hanovruslan** [doctrine/data-fixtures#301]
Question: Add more options to Purger 

HI! How about make Purger more configurable by cli options (or\and service configs in the relevant bundle)

Use cases - purge only specific entity tables (or\and rows in the specific id range) if test data consist of fixture (auto) and those created via UI

Also it might be target to doctrine orm (and so on) bundle but  .. has ability to save with specific primary key value

**Comment by Ocramius** [comment]
The purger is designed to clean anything in the defined metadata, and that's a design decision behind it. If you need a specific purger, you can write one by implementing the `PurgerInterface`
