### ISSUE TITLE
OrmPurger in LoadDataFixturesDoctrineCommand ignores dbal schema_filter

### ISSUE THREAD

**Issue by DangerLifter** [doctrine/data-fixtures#303]
I have a view which  is defined as readonly entity for query builders supporting. In dbal schema_filter there is "schema_filter: ~(?!_view)$~" which as I consider should exclude those tables from management. But running doctrine:fixtures:load still causes purging from those tables : The target table recent_product_history_view of the DELETE is not updatable

**Comment by Ocramius** [comment]
Closing here: schema management and fixture management are disjunct sets, and the option has nothing to do with loading/clearing fixtures.
