### ISSUE TITLE
Integration with zend Expressive

### ISSUE THREAD

**Issue by jl91** [doctrine/data-fixtures#304]
Hello Guys, this is John, Let me ask you one thing, there is one type of integration with zend expressive and doctrine datafixtures? i search on gist.github.com.br but o dont found anything.

**Comment by Ocramius** [comment]
data-fixtures usage is straightforward:

```php
        $loader = new Loader();
        $loader->addFixture(new Fixture1());
        $loader->addFixture(new Fixture2());
        $loader->addFixture(new Fixture3());

        (new ORMExecutor($entityManager, new ORMPurger()))
            ->execute($loader->getFixtures());
```

No need for framework integration
