### ISSUE TITLE
Entity suggestion in create command and some entity stuff in DataFixtures class

### ISSUE THREAD

**Issue by shambhu384** [doctrine/data-fixtures#307]
I personally think DataFIxtures are meant to add dummy data in an entity, so why can't we add entity suggestion and code scaffolding.

**Comment by Ocramius** [comment]
What do you mean by those two? Could you add examples of what you have in mind?

**Comment by jwage** [comment]
I think you are wanting this? https://github.com/fzaninotto/Faker

**Comment by Ocramius** [comment]
Closing here: description too vague.
