### ISSUE TITLE
ORMPurger ignores callable schemaAssetsFilter

### ISSUE THREAD

**Issue by guillaumesmo** [doctrine/data-fixtures#310]
ORMPurger completely ignores the Configuration::setSchemaAssetsFilter becauses it still relies on the deprecated setFilterSchemaAssetsExpression

With the latest Symfony DoctrineBundle, setSchemaAssetsFilter is used and deletes all schemas

See https://github.com/doctrine/DoctrineBundle/pull/935

**Comment by alcaeus** [comment]
See #312. @guillaumesmo could you let me know if this fixes your problem? Thanks!

**Comment by guillaumesmo** [comment]
@alcaeus this is indeed fixed with your branch. Tested with doctrine/doctrine-bundle 1.11.2 and doctrine/data-fixtures (dev-fix-schema-filters 92c9d05)

I also double-checked it doesn't work with doctrine/doctrine-bundle 1.11.2 and doctrine/data-fixtures v1.3.1

**Comment by alcaeus** [comment]
Wonderful, thank you! I’ll tag a release soon.

**Comment by alcaeus** [comment]
1.3.2 has been released. Thanks for reporting this!
