### ISSUE TITLE
Question: doctrine/mongodb-odm 2.0

### ISSUE THREAD

**Issue by shehi** [doctrine/data-fixtures#327]
As composer.json of this package indicates, it only works with mongodb-odm 1.x. So question is: what we use for mongodb-odm 2.0? 

Additionally docs here: https://symfony.com/doc/current/bundles/DoctrineFixturesBundle/index.html mention only ORM, whereas this package (which is the same package that bundle uses) mentions both ORM and ODM. So, which is it? ORM-only or both?

There are so many questions regarding fixture loading in ODM, I can't decide which tech to use. Unfortunately I can't use Alice tooling as it gets completely messed up when a project has both ORM and ODM assets. I'd really appreciate if someone could clarify what are the best tools for fixture loading in mongodb-odm 2.x arena. Thanks.

**Comment by alcaeus** [comment]
The composer requirement only pertains to the tests which haven't been updated to use ODM 2.0 yet. Since dev dependencies aren't evaluated when you require the package in your project, you should be able to use it just fine. In fact, version 4.0 of the ODM bundle (which uses ODM 2.0) requires this package as part of its dev dependencies to test the fixture loading functionality and it works just fine: https://github.com/doctrine/DoctrineMongoDBBundle/blob/cf27f727b4a24f75bc3ac7f2c5bc33242c211331/composer.json#L27

**Comment by shehi** [comment]
So, this package effectively isn't being tested and that badge in readme file is just a bogus? WOW.

Can someone please update related docs to reflect the fact that related libs work with ODM as well please? Thanks.

P.S.: Please close this if you think there is nothing to be done.

**Comment by alcaeus** [comment]
> So, this package effectively isn't being tested and that badge in readme file is just a bogus? WOW.

Please be more considerate when you word things. As is, the sentence is quite hurtful.

You'll be happy to know that the object management logic hasn't changed between ODM 1.x and 2.x. The package is also being tested by the various versions of DoctrineMongoDBBundle that include it in their test suite. This bundle currently tests against ODM 1.x as that is still used by most people. We'll update the test suite to use ODM 2.x in due time.

> Can someone please update related docs to reflect the fact that related libs work with ODM as well please? Thanks.

Be the change you want to see in the world. In other words, feel free to submit a pull request. Thank you.

**Comment by shehi** [comment]
@alcaeus , I am open source developer myself and what you just stated above , with all due respect, are BS:
1) Putting green badge on a readme of the package which implies this package is tested, whereas it is not, is an outright LIE. I can't show any kind of consideration when I am lied to. Just remove the badge from there, or put a note stating what it is for. If many use v1.x of this package, keep the badge in the readme of that release.
2) You can't ask people "to be the change they want to see" everytime. That's God-awful, indiscriminate cliche which only adds to the problem. In my case, I just started using this package, which has big documentation problems (hindering our learning of it) and also lying to us with it being tested. At this point people like me are in no position "to submit a PR". So please don't patronize us like this.

With all these said, I still thank you and the team with all the great work you guys have been done, are doing and hopefully will be doing in future. It matters a lot to us - consumers and creators alike. But please, enough with cliches and patronizing attitude. You need to be able to onboard people properly first, before asking for contributions. Thank you for your understanding!

**Comment by Ocramius** [comment]
Please refrain from contributing further to Doctrine Project.
