### ISSUE TITLE
return type class-string[] causes issues with phpstan

### ISSUE THREAD

**Issue by MattNunnBud** [doctrine/data-fixtures#339]
https://github.com/doctrine/data-fixtures/blob/265b209150ce6bfa22c3825bfcd512f5b5c32d3b/lib/Doctrine/Common/DataFixtures/DependentFixtureInterface.php#L16

When running PHPstan against my codebase in strict mode, due to the return type now being `class-string[]` rather than `array` the following errors are returned:
```
Return type (array) of method FIXTURENAME::getDependencies() should be compatible with return type (Doctrine\Common\DataFixtures\class) of method  
         Doctrine\Common\DataFixtures\DependentFixtureInterface::getDependencies() 
```

Admittedly its not a massive massive problem as we can ignore this folder for now.  But ideally the return should be of a valid type, i would suggest 
`string[]` with a comment above suggesting its the FQDN of a class

**Comment by greg0ire** [comment]
Duplicates #337

**Comment by MattNunnBud** [comment]
@greg0ire apologies, I did do a search for phpstan and Stan but nothing came up. Will close and track #337

**Comment by greg0ire** [comment]
No worries :)
