### ISSUE TITLE
Dependent fixture with no dependencies

### ISSUE THREAD

**Issue by yann-eugone** [doctrine/data-fixtures#343]
I was working on a fixture base class that determine dependencies "automatically" using entity metadata introspection.
I encountered an exception with a fixture class, implementing `DependentFixtureInterface` and method `getDependencies` returning an empty array.

This is, regarding the code, a normal behaviour : 
https://github.com/doctrine/data-fixtures/blob/master/lib/Doctrine/Common/DataFixtures/Loader.php#L301-L307
```php
$dependenciesClasses = $fixture->getDependencies();

if (! is_array($dependenciesClasses) || empty($dependenciesClasses)) {
    throw new InvalidArgumentException(sprintf('Method "%s" in class "%s" must return an array of classes which are dependencies for the fixture, and it must be NOT empty.', 'getDependencies', $fixtureClass));
}
```

But I was wondering : **should that class be considered as a regular fixture class during the sorting process ?**
This is pretty much a fixture without any dependency in the end...

If you are interested in such change, I can offer a PR.

**Comment by alcaeus** [comment]
This was discussed a couple of years ago. The simple answer is "it has always been that way", which was recently justified with "you shouldn't implement the interface if you don't have dependencies". The topic of dynamic dependencies has been dismissed, in that you should rather split the fixture classes and use common logic (e.g. by extending base classes) to avoid such dynamic dependencies in favour of explicit ones.

**Comment by yann-eugone** [comment]
I'm a bit worried of the "it has always been that way" response, but you are free to keep it like this.

For the archive, and those who read that in some time, you can just add a DummyFixture as dependency of every other, this is an ugly but perfect workaround.
