### ISSUE TITLE
add loadFromFile() method to Doctrine\Common\DataFixtures\Loader

### ISSUE THREAD

**Issue by Shreef** [doctrine/data-fixtures#40]
I was trying to load one Fixture file, but I didn't find a way to do this. currently `Doctrine\Common\DataFixtures\Loader` has only `loadFromDirectory()` method. we can refactor part of it and put it into another method to allow loading from files.

if you don't have a reason that can stop us from having a `loadFromFile()` method, just inform me and I will start working on the refactoring and will send you a pull request.

I need this to update [DoctrineFixturesBundle](https://github.com/symfony/DoctrineFixturesBundle) to be able to load from files too.

thanks

**Comment by lavoiesl** [comment]
It was merged, this issue can be closed.
