### ISSUE TITLE
Cant use an entity with ReferenceRepository if its name ends with Proxy

### ISSUE THREAD

**Issue by mdevlamynck** [doctrine/data-fixtures#417]
Since v1.6.0 our tests fail when loading fixtures for entities with a Proxy suffix in their name.

For example with the entity `Path\To\Entities\EntityProxy` we get a `Doctrine\Persistence\Mapping\MappingException: Class 'Path\To\Entities\Entity' does not exist` error.

I think the bug was introduced in https://github.com/doctrine/data-fixtures/pull/409. The `getRealClass` removes the `Proxy` suffix. Maybe the check to remove the suffix `Proxy` could be made more specific to actual proxies?

**Comment by greg0ire** [comment]
Cc @VincentLanglet

**Comment by VincentLanglet** [comment]
Maybe the custom `getRealClass` implementation should be replaced by `Doctrine\Common\Util\ClassUtils::getRealClass()`

**Comment by mdevlamynck** [comment]
I just tried it indeed fixes the issue. I'll make a PR, thx :)

**Comment by greg0ire** [comment]
This library does not have a dependency on `doctrine/common`, and I don't think we want to introduce one (we're trying to get rid of `doctrine/common` entirely).

**Comment by mdevlamynck** [comment]
You prefer simply copying the code of ClassUtils::getRealClass() in this project?

**Comment by greg0ire** [comment]
I guess
