### ISSUE TITLE
Purging of tables with multiple mapped entities

### ISSUE THREAD

**Issue by gordinskiy** [doctrine/data-fixtures#432]
|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 1.6.3

In some projects we have several mapping for one `Entity`, and some of them not have all relation declared.
In `\Doctrine\Common\DataFixtures\Purger\ORMPurger` commit order calculated for Entities, not table, so final list may contain same table in different position.

Sometimes this cause error on purge.

Can this be fixed in this package, or this case is too weird and not supported?

**Comment by stof** [comment]
having multiple tables for the same entity looks dubious to me. I think this might break more things than the ORMPurger

**Comment by derrabus** [comment]
I'm not aware that the ORM supports multiple mappings for an entity class. And as long as the ORM doesn't support it, I don't think this library should implement a hack for it.
