### ISSUE TITLE
LifecycleEventArgs::getEntity() is deprecated (used in ORMReferenceListener)

### ISSUE THREAD

**Issue by acrobat** [doctrine/data-fixtures#443]
1x: Method Doctrine\ORM\Event\LifecycleEventArgs::getEntity() is deprecated and will be removed in Doctrine ORM 3.0. Use getObject() instead. (LifecycleEventArgs.php:44 called by ORMReferenceListener.php:43, https://github.com/doctrine/orm/issues/9875, package doctrine/orm)

**Comment by greg0ire** [comment]
Are you willing to send a PR to fix this?

**Comment by acrobat** [comment]
Yeah sure, I will check it soon! Just created the issue already to keep track!

**Comment by acrobat** [comment]
@greg0ire done! See #444
