### ISSUE TITLE
Load file data

### ISSUE THREAD

**Issue by piotrantosik** [doctrine/data-fixtures#70]
It is possible to add file in fixtures data?
I have field in entity:

```php
     /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    public $imageOne;

    /**
     * @Assert\File(
     *              maxSize="100k",
     *              mimeTypes = {"image/jpg", "image/png", "image/gif"},
     *              mimeTypesMessage = "Niedozwolony plik"
     *              )
     */
    public $image;
```
and upload function something like http://symfony.com/doc/master/cookbook/doctrine/file_uploads.html
I wrote:
```php
$test = new Test();
//option 1 - error
$test->image = new \Symfony\Component\HttpFoundation\File\UploadedFile(__DIR__.'/../../../../../web/logo.png', 'logo.png');

//2 - error
$test->image = file_get_contents(__DIR__.'/../../../../../web/logo.png');

//3 - error
$test->image = __DIR__.'/../../../../../web/logo.png';
```
PHP Fatal error:  Call to a member function move() on a non-object

So, my question is - it is posible to add file with data fixtures?

**Comment by lavoiesl** [comment]
This is a Symfony specific problem, the issue should be reported to https://github.com/doctrine/DoctrineFixturesBundle or Symfony Doctrine Bridge (where there would create a cookbook/documentation)
