### ISSUE TITLE
Data Fixtures version 2.0

### ISSUE THREAD

**Issue by guilhermeblanco** [doctrine/data-fixtures#89]
Hi guys,

Here is an initial draft for evaluation for the newer version of our data fixtures code.
I'd like people to evaluate and ask whatever questions you may have on this ticket. It is not fully planned, like DependentCalculator requires a Topological sorting to prioritize which fixtures should be loaded first. Same thing for ORMPurger.
Another missing piece is the wish to use Iterators for file loading.
All that aside, the overall engineer of the tool is planned. Please evaluate and provide feedback.

Coding should start in a few days after everybody is satisfied with planned solution. I may update the diagrams during discussions on comments.

Cheers,

Guilherme Blanco

**Doctrine\Fixture**
![Doctrine_Fixture](https://f.cloud.github.com/assets/208883/147617/e562ab60-74c1-11e2-9875-fc87d1661dc3.png)

**Doctrine\Fixture\Executor**
![Doctrine_Fixture_Executor](https://f.cloud.github.com/assets/208883/147618/04b61bd2-74c2-11e2-8419-59aa695f38ae.png)

**Doctrine\Fixture\Loader**
![Doctrine_Fixture_Loader](https://f.cloud.github.com/assets/208883/147621/117ee01a-74c2-11e2-9e54-38709fcbf8b6.png)

**Doctrine\Fixture\Purger**
![Doctrine_Fixture_Purger](https://f.cloud.github.com/assets/208883/147622/1abb470e-74c2-11e2-850f-ca03c5078362.png)

**Doctrine\Fixture\Reference**
![Doctrine_Fixture_Reference](https://f.cloud.github.com/assets/208883/147624/27f83102-74c2-11e2-9eb7-21fe9c2e7684.png)

**Doctrine\Fixture\Sorter\Calculator**
![Doctrine_Fixture_Sorter_Calculator](https://f.cloud.github.com/assets/208883/147626/34967d1a-74c2-11e2-8b16-5bf645158548.png)

**Doctrine\Fixture\Sorter\Type**
![Doctrine_Fixture_Sorter_Type](https://f.cloud.github.com/assets/208883/147627/4295a2b0-74c2-11e2-9453-adb718f15369.png)

**Comment by derrabus** [comment]
We're currently planning 2.0 as a cleanup release with stronger native typing. I'm going to close this > 10 years old issue as not planned in order to avoid confusing with the _actual_ 2.0 release.
